/**
 * kbHelpers.js — Shared utilities for the Knowledge Base feature.
 *
 * Extracted from KnowledgeBasePage.jsx as part of R4 refactoring.
 * All exports are named exports (no default).
 */

// ── Available tags ────────────────────────────────────────────────────────────

/**
 * Canonical list of available KB / integration tags.
 * Tags are free-form strings generated by the LLM; this list provides
 * common suggestions that sub-components (e.g. TagEditModal) can offer
 * as quick-picks. It does NOT restrict what the user can type.
 */
export const TAGS = [
    'Sync',
    'Export',
    'Import',
    'PLM',
    'PIM',
    'DAM',
    'ERP',
    'Product Collection',
    'Enrichment INIT',
    'Data Sync',
    'Real-time',
    'Batch',
    'API',
    'Webhook',
    'Catalog',
];

// ── Tag colour mapping ────────────────────────────────────────────────────────

/**
 * Optional Tailwind colour-class overrides keyed by tag name.
 * Sub-components fall back to a default style when a tag is not listed here.
 * Extend this map as the tag vocabulary grows.
 *
 * @type {Record<string, string>}
 */
export const TAG_COLORS = {};

// ── Document status helper ────────────────────────────────────────────────────

/**
 * Return a human-readable status label for a unified KB document.
 *
 * The unified document shape (produced by normalizeKBDocs in
 * KnowledgeBasePage.jsx) carries a `source` field:
 *   - 'url'         — an HTTP/HTTPS link registered in the KB
 *   - 'uploaded'    — a file uploaded directly to the KB
 *   - 'integration' — a promoted integration spec (kb_status === "promoted")
 *
 * @param {{ source: string }} doc
 * @returns {{ label: string, variant: string }}
 */
export function getDocumentStatus(doc) {
    switch (doc.source) {
        case 'url':
            return { label: 'Link', variant: 'info' };
        case 'integration':
            return { label: 'Integration', variant: 'info' };
        case 'uploaded':
        default:
            return { label: 'Uploaded', variant: 'slate' };
    }
}

// ── File-size formatter ───────────────────────────────────────────────────────

/**
 * Format a raw byte count as a human-readable string.
 *
 * Extracted verbatim from KnowledgeBasePage.jsx (lines 28-32).
 *
 * @param {number} bytes
 * @returns {string}  e.g. "1.4 KB", "3.2 MB", "512 B"
 */
export function formatBytes(bytes) {
    if (!bytes) return '0 B';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1_048_576) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / 1_048_576).toFixed(1)} MB`;
}
