import { ExternalLink, Server, Database, Zap, ArrowRight } from 'lucide-react';
import Badge from '../ui/Badge.jsx';

const SYSTEMS = [
  {
    id: 'plm',
    name: 'PLM Mock API',
    port: 4001,
    description:
      'Product Lifecycle Management system. Source of product specifications, Bills of Materials, and Engineering Change Orders for integration processing.',
    badge: 'Source',
    badgeVariant: 'info',
    icon: Database,
    endpoints: ['GET /products', 'GET /bom/{id}', 'GET /ecn/{id}'],
    docsPath: '/docs',
  },
  {
    id: 'pim',
    name: 'PIM Mock API',
    port: 4002,
    description:
      'Product Information Management system. Target for enriched product data, extended attributes, and digital asset references generated by the integration.',
    badge: 'Target',
    badgeVariant: 'success',
    icon: Server,
    endpoints: ['POST /products', 'PUT /attributes/{id}', 'POST /assets'],
    docsPath: '/docs',
  },
];

export default function ApiSystemsPage() {
  return (
    <div className="space-y-6 max-w-4xl">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {SYSTEMS.map(sys => {
          const Icon = sys.icon;
          const docsUrl = `http://${window.location.hostname}:${sys.port}${sys.docsPath}`;
          return (
            <div
              key={sys.id}
              className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden hover:shadow-md transition-shadow"
            >
              <div className="px-5 py-4 border-b border-slate-100">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center flex-shrink-0">
                      <Icon size={18} className="text-slate-600" />
                    </div>
                    <div>
                      <p
                        className="font-semibold text-slate-900"
                        style={{ fontFamily: 'Outfit, sans-serif' }}
                      >
                        {sys.name}
                      </p>
                      <p className="text-xs text-slate-400 mt-0.5">Port {sys.port}</p>
                    </div>
                  </div>
                  <Badge variant={sys.badgeVariant}>{sys.badge}</Badge>
                </div>
              </div>

              <div className="px-5 py-4 space-y-4">
                <p className="text-sm text-slate-600 leading-relaxed">{sys.description}</p>

                <div>
                  <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">
                    Key Endpoints
                  </p>
                  <div className="space-y-1">
                    {sys.endpoints.map(ep => (
                      <div key={ep} className="flex items-center gap-2">
                        <Zap size={11} className="text-indigo-400 flex-shrink-0" />
                        <code className="text-xs text-slate-600 font-mono">{ep}</code>
                      </div>
                    ))}
                  </div>
                </div>

                <a
                  href={docsUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-xl text-sm font-medium hover:bg-indigo-700 transition-colors"
                >
                  <ExternalLink size={13} />
                  Open Swagger Docs
                </a>
              </div>
            </div>
          );
        })}
      </div>

      {/* Data flow diagram */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
        <h3
          className="font-semibold text-slate-900 mb-5"
          style={{ fontFamily: 'Outfit, sans-serif' }}
        >
          Integration Data Flow
        </h3>
        <div className="flex items-center justify-center gap-3">
          <div className="flex flex-col items-center px-6 py-4 bg-blue-50 rounded-2xl border border-blue-200 min-w-28">
            <Database size={22} className="text-blue-600 mb-2" />
            <span className="text-sm font-semibold text-blue-800">PLM</span>
            <span className="text-xs text-blue-500 mt-0.5">Source</span>
          </div>

          <div className="flex flex-col items-center gap-1.5 flex-1 max-w-40">
            <div className="flex items-center w-full">
              <div className="flex-1 h-0.5 bg-indigo-300" />
              <ArrowRight size={16} className="text-indigo-500 flex-shrink-0" />
            </div>
            <span className="text-xs text-slate-400 text-center font-medium">Integration Agent</span>
          </div>

          <div className="flex flex-col items-center px-6 py-4 bg-violet-50 rounded-2xl border border-violet-200 min-w-28">
            <div className="relative">
              <Database size={22} className="text-violet-600 mb-2" />
            </div>
            <span className="text-sm font-semibold text-violet-800">ChromaDB</span>
            <span className="text-xs text-violet-500 mt-0.5">RAG Store</span>
          </div>

          <div className="flex flex-col items-center gap-1.5 flex-1 max-w-40">
            <div className="flex items-center w-full">
              <div className="flex-1 h-0.5 bg-emerald-300" />
              <ArrowRight size={16} className="text-emerald-500 flex-shrink-0" />
            </div>
            <span className="text-xs text-slate-400 text-center font-medium">Enriched Data</span>
          </div>

          <div className="flex flex-col items-center px-6 py-4 bg-emerald-50 rounded-2xl border border-emerald-200 min-w-28">
            <Server size={22} className="text-emerald-600 mb-2" />
            <span className="text-sm font-semibold text-emerald-800">PIM</span>
            <span className="text-xs text-emerald-500 mt-0.5">Target</span>
          </div>
        </div>
      </div>
    </div>
  );
}
